### ISSUE TITLE
Missing parentheses on docker cheatsheet.

### ISSUE THREAD

**Issue by theodorosploumis** [dockerlux/dockerlux.github.io#1]
I think that in this cheatsheet https://github.com/dockerlux/dockerlux.github.io/blob/master/pdf/cheat-sheet-v2.pdf there is a missing closing parentheses for command:

```
docker rmi $(docker images \
-q -f "dangling=true")
```

Thanks for the cheatsheet!

**Comment by gcuisinier** [comment]
No, nothing is missing, but the command is split in 2 lines

Here is the equivalent in one line 
`docker rmi $(docker images -q -f "dangling=true")`

**Comment by gcuisinier** [comment]
But thank you your comment :)

**Comment by theodorosploumis** [comment]
I didn't know that there is no need for closing parentheses when you change line on CL! Thank you.
